baseURL = 'http://gohugo.io/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "hello"
hostname = "gohugo.io"
  [params.author]
    name = "Hugo Nightfall"  # Website and RSS feed author
    email = "email@example.com"  # RSS feed email address


readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "twitter"
url = "https://www.example.com"
aria = "Twitter Profile"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.example.com"
aria = "LinkedIn Profile"

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"
aria = "My e-Mail Address"
