[build.environment]
  DART_SASS_VERSION = "1.70.0"
  HUGO_VERSION = "0.122.0"
  HUGO_ENV = "production"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://hugo-theme-nightfall.netlify.com"

[build]
  publish = "exampleSite/public"
  command = """\
    curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    export PATH=/opt/build/repo/dart-sass:$PATH && \
    cd exampleSite && \
    hugo --gc --minify --themesDir ../.. --theme $HUGO_THEME --baseURL $HUGO_BASEURL
    """